saa = read.csv("sa-scpa1.txt", header = FALSE, sep = ";")
sab = read.csv("sa-scpb1.txt", header = FALSE, sep = ";")
sac = read.csv("sa-scpc1.txt", header = FALSE, sep = ";")
sad = read.csv("sa-scpd1.txt", header = FALSE, sep = ";")
acoa = read.csv("aco-scpa1.txt", header = FALSE, sep = ";")
acob = read.csv("aco-scpb1.txt", header = FALSE, sep = ";")
acoc = read.csv("aco-scpc1.txt", header = FALSE, sep = ";")
acod = read.csv("aco-scpd1.txt", header = FALSE, sep = ";")

saa$V3 <- 100*(1-((saa$V2-253)/253))
sab$V3 <- 100*(1-((sab$V2-69)/69))
sac$V3 <- 100*(1-((sac$V2-227)/227))
sad$V3 <- 100*(1-((sad$V2-60)/60))
acoa$V3 <- 100*(1-((acoa$V2-253)/253))
acob$V3 <- 100*(1-((acob$V2-69)/69))
acoc$V3 <- 100*(1-((acoc$V2-227)/227))
acod$V3 <- 100*(1-((acod$V2-60)/60))

interpsaa <- approx(saa$V1, saa$V3)
interpsab <- approx(sab$V1, sab$V3)
interpsac <- approx(sac$V1, sac$V3)
interpsad <- approx(sad$V1, sad$V3)
interpacoa <- approx(acoa$V1, acoa$V3)
interpacob <- approx(acob$V1, acob$V3)
interpacoc <- approx(acoc$V1, acoc$V3)
interpacod <- approx(acod$V1, acod$V3)

modsaa <- lm(interpsaa$y ~ poly(interpsaa$x,5))
modsab <- lm(interpsab$y ~ poly(interpsab$x,5))
modsac <- lm(interpsac$y ~ poly(interpsac$x,5))
modsad <- lm(interpsad$y ~ poly(interpsad$x,5))
modacoa <- lm(interpacoa$y ~ poly(interpacoa$x,5))
modacob <- lm(interpacob$y ~ poly(interpacob$x,5))
modacoc <- lm(interpacoc$y ~ poly(interpacoc$x,5))
modacod <- lm(interpacod$y ~ poly(interpacod$x,5))

predicted.intervals.saa <- predict(model,data.frame(x=interpsaa$x),interval='confidence',level=0.99)
predicted.intervals.sab <- predict(model,data.frame(x=interpsab$x),interval='confidence',level=0.99)
predicted.intervals.sac <- predict(model,data.frame(x=interpsac$x),interval='confidence',level=0.99)
predicted.intervals.sad <- predict(model,data.frame(x=interpsad$x),interval='confidence',level=0.99)
predicted.intervals.acoa <- predict(model,data.frame(x=interpacoa$x),interval='confidence',level=0.99)
predicted.intervals.acob <- predict(model,data.frame(x=interpacob$x),interval='confidence',level=0.99)
predicted.intervals.acoc <- predict(model,data.frame(x=interpacoc$x),interval='confidence',level=0.99)
predicted.intervals.acod <- predict(model,data.frame(x=interpacod$x),interval='confidence',level=0.99)

plot(1, main="title", sub="subtitle", xlab="X-axis label", ylab="y-axix label", xlim=c(0, 50000), ylim=c(85, 100))

lines(interpsaa$x,predicted.intervals.saa[,1],col='green')
lines(interpsab$x,predicted.intervals.sab[,1],col='blue')
lines(interpsac$x,predicted.intervals.sac[,1],col='red')
lines(interpsad$x,predicted.intervals.sad[,1],col='black')
lines(interpacoa$x,predicted.intervals.acoa[,1],col='green', lwd=3)
lines(interpacob$x,predicted.intervals.acob[,1],col='blue', lwd=3)
lines(interpacoc$x,predicted.intervals.acoc[,1],col='red', lwd=3)
lines(interpacod$x,predicted.intervals.acod[,1],col='black', lwd=3)


plot(1, main="Quality - Time", xlab="CPU - Time (milliseconds)", ylab="Quality (%)", xlim=c(0, 55000), ylim=c(85, 100))

lines(interpsaa$x,predicted.intervals.saa[,1],col='green')
lines(interpsab$x,predicted.intervals.sab[,1],col='blue')
lines(interpsac$x,predicted.intervals.sac[,1],col='red')
lines(interpsad$x,predicted.intervals.sad[,1],col='black')
lines(interpacoa$x,predicted.intervals.acoa[,1],col='green', type="c")
lines(interpacob$x,predicted.intervals.acob[,1],col='blue', type="c")
lines(interpacoc$x,predicted.intervals.acoc[,1],col='red', type="c")
lines(interpacod$x,predicted.intervals.acod[,1],col='black', type="c")


legend(1, 95, legend=c("SA - SCPA1", "SA - SCPB1", "SA - SCPC1", "SA - SCPD1", "ACO - SCPA1", "ACO - SCPB1", "ACO - SCPC1", "ACO - SCPD1"), col=c("green", "blue", "red", "black", "green", "blue", "red", "black"), lty=c(1,1,1,1,2,2,2,2), cex=0.8)